Add node role for zonal EFS volumes

diff --git a/assets/overlays/aws-efs/patches/node_add_driver.yaml b/assets/overlays/aws-efs/patches/node_add_driver.yaml
--- a/assets/overlays/aws-efs/patches/node_add_driver.yaml
+++ b/assets/overlays/aws-efs/patches/node_add_driver.yaml
@@ -30,6 +30,46 @@ spec:
         - operator: Exists
       nodeSelector:
         kubernetes.io/os: linux
+      initContainers:
+        - name: init-aws-credentials-file
+          image: ${TOOLS_IMAGE}
+          command:
+          - sh
+          - -c
+          - |
+            # Define file path variables
+            CREDENTIALS_FILE=/var/run/aws/keys/credentials
+            AUTH_CREDENTIALS_FILE=/var/run/aws/auth/credentials
+            AWS_ACCESS_KEY_ID_FILE=/var/run/aws/keys/aws_access_key_id
+            AWS_SECRET_ACCESS_KEY_FILE=/var/run/aws/keys/aws_secret_access_key
+
+            # If credentials key exists in ebs-cloud-credentials secret, then use it as the auth file
+            if [ -e "$CREDENTIALS_FILE" ]; then
+                cp "$CREDENTIALS_FILE" "$AUTH_CREDENTIALS_FILE"
+                echo "Kubernetes Secret already contains credentials file, copied to the right place: $AUTH_CREDENTIALS_FILE"
+                exit 0
+            fi
+
+            # Otherwise, make sure the access keys are mounted in the pod...
+            if [ ! -e "$AWS_ACCESS_KEY_ID_FILE" ] || [ ! -e "$AWS_SECRET_ACCESS_KEY_FILE" ]; then
+                echo "AWS keys not found"
+                exit 1
+            fi
+
+            # And create an auth file based on those keys
+            cat <<-EOF > "$AUTH_CREDENTIALS_FILE"
+            [default]
+            aws_access_key_id=$(cat "$AWS_ACCESS_KEY_ID_FILE")
+            aws_secret_access_key=$(cat "$AWS_SECRET_ACCESS_KEY_FILE")
+            EOF
+            echo "Kubernetes Secret does not have credentials file, created a fresh one at $AUTH_CREDENTIALS_FILE"
+          volumeMounts:
+            - name: aws-keys
+              mountPath: /var/run/aws/keys
+              readOnly: true
+            - name: aws-auth
+              mountPath: /var/run/aws/auth
+          terminationMessagePolicy: FallbackToLogsOnError
       containers:
         - name: csi-driver
           securityContext:
@@ -42,6 +82,10 @@ spec:
           env:
             - name: CSI_ENDPOINT
               value: unix:/csi/csi.sock
+            - name: AWS_SDK_LOAD_CONFIG
+              value: '1'
+            - name: AWS_CONFIG_FILE
+              value: /var/run/aws/auth/credentials
           volumeMounts:
             - name: kubelet-dir
               mountPath: /var/lib/kubelet
@@ -58,6 +102,12 @@ spec:
               mountPath: /etc/selinux
             - name: sys-fs
               mountPath: /sys/fs
+            - name: aws-auth
+              mountPath: /var/run/aws/auth
+              readOnly: true
+            - name: bound-sa-token
+              mountPath: /var/run/secrets/openshift/serviceaccount
+              readOnly: true
           ports:
             - name: healthz
               # Due to hostNetwork, this port is open on all nodes!
@@ -159,3 +209,16 @@ spec:
           hostPath:
             path: /sys/fs
             type: Directory
+        - name: aws-keys
+          secret:
+            secretName: node-aws-efs-cloud-credentials
+        - name: aws-auth
+          emptyDir: {}
+        # This service account token can be used to provide identity outside the cluster.
+        # For example, this token can be used with AssumeRoleWithWebIdentity to authenticate with AWS using IAM OIDC provider and STS.
+        - name: bound-sa-token
+          projected:
+            sources:
+              - serviceAccountToken:
+                  path: token
+                  audience: openshift
